// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package librairie.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Librairie module
	public static java.math.BigDecimal calculMontantTotalProduit(IContext context, librairie.proxies.Livre _livre)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Livre", _livre == null ? null : _livre.getMendixObject());
		return (java.math.BigDecimal) Core.microflowCall("Librairie.CalculMontantTotalProduit").withParams(params).execute(context);
	}
	public static void create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Librairie.Create").withParams(params).execute(context);
	}
	public static void delete(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Librairie.Delete").withParams(params).execute(context);
	}
	public static void read(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Librairie.Read").withParams(params).execute(context);
	}
	public static void update(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Librairie.Update").withParams(params).execute(context);
	}
}