// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package librairie.proxies;

public class Auteur
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject auteurMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Librairie.Auteur";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nom("Nom"),
		Pays("Pays");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Auteur(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Librairie.Auteur"));
	}

	protected Auteur(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject auteurMendixObject)
	{
		if (auteurMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Librairie.Auteur", auteurMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Librairie.Auteur");

		this.auteurMendixObject = auteurMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Auteur.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static librairie.proxies.Auteur initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return librairie.proxies.Auteur.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static librairie.proxies.Auteur initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new librairie.proxies.Auteur(context, mendixObject);
	}

	public static librairie.proxies.Auteur load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return librairie.proxies.Auteur.initialize(context, mendixObject);
	}

	public static java.util.List<librairie.proxies.Auteur> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<librairie.proxies.Auteur> result = new java.util.ArrayList<librairie.proxies.Auteur>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Librairie.Auteur" + xpathConstraint))
			result.add(librairie.proxies.Auteur.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Nom
	 */
	public final java.lang.String getNom()
	{
		return getNom(getContext());
	}

	/**
	 * @param context
	 * @return value of Nom
	 */
	public final java.lang.String getNom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nom.toString());
	}

	/**
	 * Set value of Nom
	 * @param nom
	 */
	public final void setNom(java.lang.String nom)
	{
		setNom(getContext(), nom);
	}

	/**
	 * Set value of Nom
	 * @param context
	 * @param nom
	 */
	public final void setNom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nom)
	{
		getMendixObject().setValue(context, MemberNames.Nom.toString(), nom);
	}

	/**
	 * @return value of Pays
	 */
	public final java.lang.String getPays()
	{
		return getPays(getContext());
	}

	/**
	 * @param context
	 * @return value of Pays
	 */
	public final java.lang.String getPays(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Pays.toString());
	}

	/**
	 * Set value of Pays
	 * @param pays
	 */
	public final void setPays(java.lang.String pays)
	{
		setPays(getContext(), pays);
	}

	/**
	 * Set value of Pays
	 * @param context
	 * @param pays
	 */
	public final void setPays(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pays)
	{
		getMendixObject().setValue(context, MemberNames.Pays.toString(), pays);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return auteurMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final librairie.proxies.Auteur that = (librairie.proxies.Auteur) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Librairie.Auteur";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
