// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package librairie.proxies;

public class Livre
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject livreMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Librairie.Livre";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Titre("Titre"),
		Prix("Prix"),
		Quantite("Quantite"),
		MontantTotal("MontantTotal"),
		Livre_Auteur("Librairie.Livre_Auteur");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Livre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Librairie.Livre"));
	}

	protected Livre(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject livreMendixObject)
	{
		if (livreMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Librairie.Livre", livreMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Librairie.Livre");

		this.livreMendixObject = livreMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Livre.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static librairie.proxies.Livre initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return librairie.proxies.Livre.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static librairie.proxies.Livre initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new librairie.proxies.Livre(context, mendixObject);
	}

	public static librairie.proxies.Livre load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return librairie.proxies.Livre.initialize(context, mendixObject);
	}

	public static java.util.List<librairie.proxies.Livre> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<librairie.proxies.Livre> result = new java.util.ArrayList<librairie.proxies.Livre>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Librairie.Livre" + xpathConstraint))
			result.add(librairie.proxies.Livre.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Titre
	 */
	public final java.lang.String getTitre()
	{
		return getTitre(getContext());
	}

	/**
	 * @param context
	 * @return value of Titre
	 */
	public final java.lang.String getTitre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Titre.toString());
	}

	/**
	 * Set value of Titre
	 * @param titre
	 */
	public final void setTitre(java.lang.String titre)
	{
		setTitre(getContext(), titre);
	}

	/**
	 * Set value of Titre
	 * @param context
	 * @param titre
	 */
	public final void setTitre(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titre)
	{
		getMendixObject().setValue(context, MemberNames.Titre.toString(), titre);
	}

	/**
	 * @return value of Prix
	 */
	public final java.math.BigDecimal getPrix()
	{
		return getPrix(getContext());
	}

	/**
	 * @param context
	 * @return value of Prix
	 */
	public final java.math.BigDecimal getPrix(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Prix.toString());
	}

	/**
	 * Set value of Prix
	 * @param prix
	 */
	public final void setPrix(java.math.BigDecimal prix)
	{
		setPrix(getContext(), prix);
	}

	/**
	 * Set value of Prix
	 * @param context
	 * @param prix
	 */
	public final void setPrix(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prix)
	{
		getMendixObject().setValue(context, MemberNames.Prix.toString(), prix);
	}

	/**
	 * @return value of Quantite
	 */
	public final java.lang.Integer getQuantite()
	{
		return getQuantite(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantite
	 */
	public final java.lang.Integer getQuantite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantite.toString());
	}

	/**
	 * Set value of Quantite
	 * @param quantite
	 */
	public final void setQuantite(java.lang.Integer quantite)
	{
		setQuantite(getContext(), quantite);
	}

	/**
	 * Set value of Quantite
	 * @param context
	 * @param quantite
	 */
	public final void setQuantite(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantite)
	{
		getMendixObject().setValue(context, MemberNames.Quantite.toString(), quantite);
	}

	/**
	 * @return value of MontantTotal
	 */
	public final java.math.BigDecimal getMontantTotal()
	{
		return getMontantTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of MontantTotal
	 */
	public final java.math.BigDecimal getMontantTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MontantTotal.toString());
	}

	/**
	 * Set value of MontantTotal
	 * @param montanttotal
	 */
	public final void setMontantTotal(java.math.BigDecimal montanttotal)
	{
		setMontantTotal(getContext(), montanttotal);
	}

	/**
	 * Set value of MontantTotal
	 * @param context
	 * @param montanttotal
	 */
	public final void setMontantTotal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal montanttotal)
	{
		getMendixObject().setValue(context, MemberNames.MontantTotal.toString(), montanttotal);
	}

	/**
	 * @return value of Livre_Auteur
	 */
	public final librairie.proxies.Auteur getLivre_Auteur() throws com.mendix.core.CoreException
	{
		return getLivre_Auteur(getContext());
	}

	/**
	 * @param context
	 * @return value of Livre_Auteur
	 */
	public final librairie.proxies.Auteur getLivre_Auteur(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		librairie.proxies.Auteur result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Livre_Auteur.toString());
		if (identifier != null)
			result = librairie.proxies.Auteur.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Livre_Auteur
	 * @param livre_auteur
	 */
	public final void setLivre_Auteur(librairie.proxies.Auteur livre_auteur)
	{
		setLivre_Auteur(getContext(), livre_auteur);
	}

	/**
	 * Set value of Livre_Auteur
	 * @param context
	 * @param livre_auteur
	 */
	public final void setLivre_Auteur(com.mendix.systemwideinterfaces.core.IContext context, librairie.proxies.Auteur livre_auteur)
	{
		if (livre_auteur == null)
			getMendixObject().setValue(context, MemberNames.Livre_Auteur.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Livre_Auteur.toString(), livre_auteur.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return livreMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final librairie.proxies.Livre that = (librairie.proxies.Livre) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Librairie.Livre";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
